CREATE SCHEMA project;

CREATE TABLE project.ORDER_PARAMS (
    ORDER_ID  SERIAL   PRIMARY KEY,
    WEIGHT    NUMERIC  NOT NULL,
    HEIGHT    NUMERIC  NOT NULL,
    WIDTH     NUMERIC  NOT NULL,
    DEPTH     NUMERIC  NOT NULL
);

CREATE TABLE project.ORDER (
    ORDER_ID     SERIAL        PRIMARY KEY,
    CLIENT_ID    SERIAL        NOT NULL,
    "FROM"      VARCHAR(512)  NOT NULL,
    "TO"         VARCHAR(512)  NOT NULL,
    PRICE        NUMERIC       NOT NULL,
    DISPATCH_DT  DATE          NOT NULL,
    ARRIVAL_DT   DATE          NOT NULL
);

CREATE TABLE project.CLIENT (
    CLIENT_ID       SERIAL        PRIMARY KEY,
    CLIENT_NM       VARCHAR(512)  NOT NULL,
    PHONE_NUM       VARCHAR(20)   NOT NULL,
    DISCOUNT_COEFF  NUMERIC       NOT NULL
);

CREATE TABLE project.TRANSPORT (
    TRANSPORT_ID  SERIAL        PRIMARY KEY,
    "TYPE"        VARCHAR(512)  NOT NULL,
    CAPACITY      NUMERIC       NOT NULL
);

CREATE TABLE project.INTERM_DELIVERY (
    ORDER_ID      SERIAL  NOT NULL,
    TRANSPORT_ID  SERIAL  NOT NULL,
    FROM_ID       SERIAL  NOT NULL,
    TO_ID         SERIAL  NOT NULL
);

CREATE TABLE project.TRANSPORT_STUFF (
    EMPL_ID       SERIAL        NOT NULL,
    TRANSPORT_ID  SERIAL        NOT NULL,
    "FUNCTION"    VARCHAR(512)  NOT NULL
);

CREATE TABLE project.EMPLOYEE (
    EMPL_ID  SERIAL        PRIMARY KEY,
    EMPL_NM  VARCHAR(512)  NOT NULL,
    SALARY   NUMERIC       NOT NULL
);

CREATE TABLE project.STOCK (
    STOCK_ID   SERIAL   PRIMARY KEY,
    CITY       VARCHAR(512)  NOT NULL,
    TYPE       VARCHAR(512)  NOT NULL,
    CAPACITY   NUMERIC  NOT NULL
);

CREATE TABLE project.STOCK_STUFF (
    EMPL_ID     SERIAL        NOT NULL,
    STOCK_ID    SERIAL        NOT NULL,
    "FUNCTION"  VARCHAR(512)  NOT NULL
);
